// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tmxelvnlrgnvwesyikos.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRteGVsdm5scmdudndlc3lpa29zIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg3ODA3OTUsImV4cCI6MjA3NDM1Njc5NX0.kCnyWb5EJItkurxC_tuyeldEpSaU26WKvNESBz2DNE4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});